force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Poke_Id__c.field-meta.xml
<CustomField>
    <fullName>Poke_Id__c</fullName>
    <externalId>true</externalId>
    <label>Poke Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/SpriteURL__c.field-meta.xml
<CustomField>
    <fullName>SpriteURL__c</fullName>
    <label>SpriteURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PokeCardController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-14-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PokeCardController {
    @AuraEnabled
    public static void savePokemon(String name, String spriteURL, String pokeId) {
        upsert new Pokemon__c(
            Name = name ,
            SpriteURL__c = spriteURL,
            Poke_Id__c = pokeId
        );
    }
}